language: java
dist: trusty

jdk: openjdk8

git:
  depth: false

addons:
  sonarcloud:
    organization: retest
    token: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

script: ci/script.sh

before_deploy: ci/before_deploy.sh

deploy:
  - provider: script
    script: ci/deploy.sh
    on:
      tags: true
  - provider: releases
    api_key: "${GH_TOKEN}"
    draft: true
    on:
      tags: true
